<script setup lang="ts">
import type { KeyPairKind } from '~/utils/crypto'

definePageMeta({
  tool: {
    title: 'Secrets & Keys',
    description: 'API keys, UUIDs, AES keys and real ECDSA/RSA key pairs in PEM — generated by the browser, never sent anywhere.',
    icon: 'i-lucide-key',
    category: 'Security',
    keywords: ['api key', 'uuid', 'guid', 'nonce', 'token', 'aes', 'rsa', 'ecdsa', 'pem', 'keypair', 'entropy'],
    order: 50
  }
})

const { copy } = useCopy()

const supported = ref(true)
onMounted(() => (supported.value = subtleAvailable()))

/* --------------------------------------------------------------- secrets */

type Format = 'hex' | 'base64' | 'base64url' | 'alphanumeric'

const settings = useStored('keys', { bytes: 32, format: 'base64url' as Format, count: 3, prefix: '' })
const secrets = ref<string[]>([])

const formats: Array<{ label: string; value: Format }> = [
  { label: 'Hex', value: 'hex' },
  { label: 'Base64', value: 'base64' },
  { label: 'Base64url', value: 'base64url' },
  { label: 'Alphanumeric', value: 'alphanumeric' }
]

const ALPHANUMERIC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'

function encodeSecret(bytes: Uint8Array, format: Format) {
  switch (format) {
    case 'hex': return toHex(bytes)
    case 'base64': return toBase64(bytes)
    case 'base64url': return toBase64(bytes, true)
    default: return Array.from(bytes, byte => ALPHANUMERIC[byte % ALPHANUMERIC.length]).join('')
  }
}

function generateSecrets() {
  const size = Math.max(8, Math.min(128, Math.floor(settings.value.bytes) || 32))
  const count = Math.max(1, Math.min(20, Math.floor(settings.value.count) || 1))

  secrets.value = Array.from({ length: count }, () => settings.value.prefix + encodeSecret(randomBytes(size), settings.value.format))
}

/** Alphanumeric mapping loses a little entropy to modulo bias on the last symbols. */
const secretEntropy = computed(() => {
  const size = Math.max(8, Math.min(128, Math.floor(settings.value.bytes) || 32))
  return settings.value.format === 'alphanumeric'
    ? Math.round(size * Math.log2(ALPHANUMERIC.length))
    : size * 8
})

/* ----------------------------------------------------------------- uuids */

const uuids = ref<string[]>([])
function generateUuids() {
  uuids.value = Array.from({ length: 5 }, () => uuid())
}

/* --------------------------------------------------------------- aes key */

const aesBits = ref<128 | 256>(256)
const aesKey = ref('')
function generateAesKey() {
  aesKey.value = toBase64(randomBytes(aesBits.value / 8))
}

/* -------------------------------------------------------------- key pair */

const kind = ref<KeyPairKind>('ECDSA-P256')
const pair = ref<{ publicKey: string; privateKey: string } | null>(null)
const generating = ref(false)
const pairError = ref('')

async function generatePair() {
  generating.value = true
  pairError.value = ''
  pair.value = null

  try {
    pair.value = await generateKeyPair(kind.value)
  } catch (thrown) {
    pairError.value = thrown instanceof Error
      ? `${kind.value} is not supported by this browser (${thrown.message})`
      : 'Key generation failed.'
  } finally {
    generating.value = false
  }
}

onMounted(() => {
  generateSecrets()
  generateUuids()
  generateAesKey()
})
</script>

<template>
  <ToolPage wide>
    <UAlert
      v-if="!supported"
      icon="i-lucide-shield-alert"
      color="warning"
      variant="subtle"
      title="Web Crypto is unavailable"
      description="Key generation needs a secure context. Open this page over https or on localhost."
    />

    <ToolPanel title="Random secrets" icon="i-lucide-key" :description="`${secretEntropy} bits of entropy per secret`">
      <template #actions>
        <UButton icon="i-lucide-refresh-cw" size="xs" label="Generate" @click="generateSecrets" />
      </template>

      <div class="grid gap-3 sm:grid-cols-4">
        <UFormField label="Bytes">
          <UInput v-model.number="settings.bytes" type="number" min="8" max="128" class="w-full" />
        </UFormField>
        <UFormField label="Format">
          <USelect v-model="settings.format" :items="formats" value-key="value" class="w-full" />
        </UFormField>
        <UFormField label="How many">
          <UInput v-model.number="settings.count" type="number" min="1" max="20" class="w-full" />
        </UFormField>
        <UFormField label="Prefix" hint="optional">
          <UInput v-model="settings.prefix" placeholder="sk_live_" class="w-full" :ui="{ base: 'font-mono' }" />
        </UFormField>
      </div>

      <ul v-if="secrets.length" class="mt-4 flex flex-col gap-1.5">
        <li
          v-for="(value, index) in secrets"
          :key="index"
          class="flex items-center gap-2 rounded-lg bg-elevated/60 px-3 py-2"
        >
          <code class="min-w-0 flex-1 break-all font-mono text-sm text-highlighted">{{ value }}</code>
          <UButton icon="i-lucide-copy" color="neutral" variant="ghost" size="xs" @click="copy(value)" />
        </li>
      </ul>
    </ToolPanel>

    <div class="grid gap-4 lg:grid-cols-2">
      <ToolPanel title="UUID v4" icon="i-lucide-hash">
        <template #actions>
          <UButton icon="i-lucide-refresh-cw" color="neutral" variant="ghost" size="xs" @click="generateUuids" />
        </template>

        <ul class="flex flex-col gap-1">
          <li v-for="value in uuids" :key="value" class="flex items-center gap-2">
            <code class="min-w-0 flex-1 truncate font-mono text-sm text-highlighted">{{ value }}</code>
            <UButton icon="i-lucide-copy" color="neutral" variant="ghost" size="xs" @click="copy(value)" />
          </li>
        </ul>

        <template #footer>
          <UButton
            icon="i-lucide-copy"
            color="neutral"
            variant="ghost"
            size="xs"
            label="Copy all"
            @click="copy(uuids.join('\n'))"
          />
        </template>
      </ToolPanel>

      <ToolPanel title="AES key" icon="i-lucide-lock" description="Raw symmetric key, base64 encoded">
        <div class="flex items-end gap-2">
          <UFormField label="Size" class="w-32">
            <USelect v-model.number="aesBits" :items="[128, 256]" class="w-full" />
          </UFormField>
          <UButton icon="i-lucide-refresh-cw" color="neutral" variant="subtle" label="New key" @click="generateAesKey" />
        </div>

        <div class="mt-3 flex items-center gap-2 rounded-lg bg-elevated/60 px-3 py-2">
          <code class="min-w-0 flex-1 break-all font-mono text-sm text-highlighted">{{ aesKey }}</code>
          <UButton icon="i-lucide-copy" color="neutral" variant="ghost" size="xs" @click="copy(aesKey)" />
        </div>
      </ToolPanel>
    </div>

    <ToolPanel title="Key pair" icon="i-lucide-key-square" description="Exported as PEM — SPKI public, PKCS#8 private">
      <div class="flex flex-wrap items-end gap-3">
        <UFormField label="Type" class="w-56">
          <USelect v-model="kind" :items="KEY_PAIR_KINDS" value-key="id" label-key="label" class="w-full" />
        </UFormField>
        <UButton
          icon="i-lucide-sparkles"
          label="Generate key pair"
          :loading="generating"
          :disabled="!supported"
          @click="generatePair"
        />
        <p class="pb-2 text-xs text-dimmed">RSA 4096 can take a few seconds.</p>
      </div>

      <p v-if="pairError" class="mt-3 text-sm text-error">{{ pairError }}</p>

      <div v-if="pair" class="mt-4 grid gap-4 lg:grid-cols-2">
        <div>
          <div class="mb-1.5 flex items-center justify-between">
            <span class="text-xs font-semibold uppercase tracking-wider text-dimmed">Public key</span>
            <UButton icon="i-lucide-copy" color="neutral" variant="ghost" size="xs" @click="copy(pair.publicKey)" />
          </div>
          <pre class="max-h-64 overflow-auto rounded-lg bg-elevated/60 p-3 font-mono text-[11px] leading-relaxed text-highlighted">{{ pair.publicKey }}</pre>
        </div>

        <div>
          <div class="mb-1.5 flex items-center justify-between">
            <span class="text-xs font-semibold uppercase tracking-wider text-dimmed">Private key</span>
            <UButton icon="i-lucide-copy" color="neutral" variant="ghost" size="xs" @click="copy(pair.privateKey)" />
          </div>
          <pre class="max-h-64 overflow-auto rounded-lg bg-elevated/60 p-3 font-mono text-[11px] leading-relaxed text-highlighted">{{ pair.privateKey }}</pre>
        </div>
      </div>

      <template #footer>
        The private key exists only in this tab. Close the page and it is gone — save it somewhere safe first.
      </template>
    </ToolPanel>
  </ToolPage>
</template>
